# Generated by Django 2.2.28 on 2022-05-24 01:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('event_code', models.UUIDField(default=uuid.UUID('1bbb10e9-8a3e-477f-be6a-dd628841c1d2'), editable=False)),
                ('event_code_short', models.CharField(default='6wFCRrX', max_length=10)),
                ('event_name', models.CharField(max_length=55, null=True)),
                ('event_location', models.CharField(max_length=30, null=True)),
                ('event_org', models.CharField(max_length=30, null=True)),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('event_image', models.ImageField(upload_to='')),
                ('about_event', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Users',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=30, null=True)),
                ('user_lname', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Socials',
            fields=[
                ('social_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('twitter', models.CharField(max_length=30, null=True)),
                ('instagram', models.CharField(max_length=30, null=True)),
                ('snapchat', models.CharField(max_length=30, null=True)),
                ('Facebook', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('user_bio', models.TextField(max_length=255, null=True)),
                ('is_event_host', models.BooleanField(default=False)),
                ('is_event_performer', models.BooleanField(default=False)),
                ('is_event_guest', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.CharField(max_length=50, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('host', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users')),
                ('social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Socials')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(editable=False, max_length=12, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('user_id', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event_Socials'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users'),
        ),
    ]
