# Generated by Django 2.2.28 on 2022-05-24 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220524_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('bb414acd-23c7-4f9c-93c7-de53e0a926a2'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='bL4jMsd', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Socials'),
        ),
    ]
