# Generated by Django 2.2.28 on 2022-07-07 00:43

from django.db import migrations, models
import event.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20220524_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default=event.models.Event.short_unique, max_length=10),
        ),
    ]
