# Generated by Django 4.0.4 on 2022-07-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_event_code_alter_event_event_code_short_and_more'),
        ('event', '0005_auto_20220707_0043'),
    ]

    operations = [
    ]
