# Generated by Django 4.0.4 on 2022-08-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_event_socials_is_event_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_users',
            name='is_event_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_users',
            name='is_event_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_users',
            name='is_event_performer',
            field=models.BooleanField(default=False),
        ),
    ]
